# Mod
mod_id = hardcorerevival
mod_name = Hardcore Revival
mod_author = BlayTheNinth
credits = BlayTheNinth
description=Help your friends back up after they die (if you can make it in time).
version = 26.1.2.1
group = net.blay09.mods
homepage=https://mods.twelveiterations.com/mc/hardcore-revival
sources=https://github.com/TwelveIterations/HardcoreRevival
issues=https://github.com/TwelveIterations/HardcoreRevival/issues
discord = https://discord.gg/VAfZ2Nau6j
license=All Rights Reserved

# Publishing
curseforge_project_id = 274036
curseforge_environments = Client,Server
modrinth_project_id = HqKoXaXz
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Build
java_version = 25
neoforge_snapshot_url =
include_fabric=true
include_neoforge=true
include_forge=false

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
