@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.blay09.mods.hardcorerevival;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;