dependencies {
    implementation("net.blay09.mods:balm-neoforge:${balm_version}") {
        changing = balm_version.contains("SNAPSHOT")
    }
    api("net.blay09.mods:shogi-api:${shogi_version}")
    jarJar("net.blay09.mods:shogi-api") {
        version {
            prefer shogi_version
        }
    }
    compileOnly("top.theillusivec4.curios:curios-neoforge:9.2.2+1.21.1:api")
}
